ArdentHQ/dashbrd

- CODE_OF_CONDUCT.md
- app/Console/Commands/InteractsWithCollections.php
- tests/App/Console/Commands/FetchCollectionNftsTest.php
https://app.clickup.com/t/861n9z7m9
Only happened when there were more than 100 (chunk size) rows. I checked our other usages of chunkById, but they all seem to be fine, because they don't join multiple tables in the first place.
-   [ ] Ready …
> fix: FetchCollectionNfts ambiguous id column

- .gitignore
- storage/debugbar/.gitignore
- storage/logs/.gitignore
Fixup to ignore log files in `/storage/debugbar/` and `/storage/logs/`
> chore: include storage gitignore files

- app/Jobs/FetchEnsDetails.php
- tests/App/Jobs/FetchEnsDetailsTest.php
Closes https://app.clickup.com/t/861na32ku
> fix: exception when ens address changes

- app/Http/Controllers/LandingPageDataController.php
- routes/api.php
- tests/App/Http/Controllers/LandingPageDataControllerTest.php
Closes https://app.clickup.com/t/865d08nt1
> feat: landing page data api endpoint

- queries/gallery.calculate_value.sql
- tests/App/Models/GalleryTest.php
Closes https://app.clickup.com/t/861na33uf, see comments on ticket
> fix: gallery value can be null

- resources/js/Hooks/useLikes.ts
Currently users cannot like galleries, related to comment https://github.com/ArdentHQ/dashbrd/pull/15#discussion_r1317395930
> fix: rollback like toggle

- app/Providers/Filament/AdminPanelProvider.php
https://app.clickup.com/t/861narcck
> refactor: remove some widgets from filament dashbard

- resources/js/Pages/Collections/Nfts/Components/TraitsCarousel/TraitsCarousel.tsx
Kickback of https://app.clickup.com/t/861namx0v
> refactor: background color for nft properties

- app/Http/Controllers/Auth/AuthenticatedSessionController.php
- app/Http/Controllers/OnboardingController.php
- app/Http/Middleware/Authenticate.php
- app/Http/Middleware/ValidateWallet.php
- resources/js/Components/Layout/Navbar.tsx
- resources/js/Components/Navbar/AppMenu.test.tsx
- resources/js/Components/Navbar/AppMenu.tsx
- resources/js/Components/Navbar/MobileMenu.tsx
- routes/web.php
- tests/App/Http/Controllers/AuthenticatedSessionControllerTest.php
- tests/App/Http/Controllers/OnboardingControllerTest.php
- tests/App/Http/Controllers/TokenControllerTest.php
https://app.clickup.com/t/861nardfa
> refactor: make galleries the default page

- app/Http/Controllers/CollectionController.php
- resources/js/Components/Collections/CollectionHeader/CollectionHeaderBottom.tsx
- routes/web.php
- tests/App/Http/Controllers/CollectionControllerTest.php
https://app.clickup.com/t/861naue4m
> fix: show login overlay for collections as guest user

- .github/release.yml
- `release.yml` from [Arkscan](https://github.com/ArdentHQ/arkscan/blob/develop/.github/release.yml) is being added.
> feat: add release.yml

- app/Console/Kernel.php
https://app.clickup.com/t/861nayyca
> chore: prune failed jobs automatically

- app/Support/Web3NftHandler.php
- tests/App/Jobs/FetchWalletNftsTest.php
Closes https://app.clickup.com/t/861nbc3f8
> fix: avoid collection's last indexed token number becoming null

- app/Data/Web3/Web3NftData.php
- app/Http/Client/Alchemy/AlchemyPendingRequest.php
- app/Http/Controllers/CollectionController.php
- app/Jobs/FetchCollectionBanner.php
- app/Models/Collection.php
- database/seeders/LiveUserSeeder.php
https://app.clickup.com/t/861nbgpah
> fix: improve types and handling for storing collection's banner_update_at

- app/Http/Controllers/CollectionController.php
- tests/App/Http/Controllers/CollectionControllerTest.php
https://app.clickup.com/t/861nbhc8h
> fix: improve collection banner update logic

- resources/js/Components/Collections/CollectionActivityTable/CollectionActivityTable.blocks.test.tsx
- resources/js/Components/Collections/CollectionActivityTable/CollectionActivityTable.blocks.tsx
- resources/js/Utils/dates.ts
Closes: https://app.clickup.com/t/861nbc69t
-   [x] Tests _(if necessary)_
> fix: format timestamp for guests

- resources/js/Components/Collections/Nfts/NftImage/NftImage.test.tsx
- resources/js/Components/Collections/Nfts/NftImage/NftImage.tsx
https://app.clickup.com/t/8678u2n5z
> fix: handle nft metadata refresh for guests

- app/Jobs/FetchCollectionNfts.php
- app/Models/Collection.php
- database/factories/CollectionFactory.php
- resources/types/generated.d.ts
- tests/App/Jobs/FetchCollectionNftsTest.php
https://app.clickup.com/t/8678uhwnf
> fix: ignore large collections in background job

- app/Console/Commands/FetchWalletNfts.php
- app/Console/Commands/LiveDumpWallets.php
- app/Console/Commands/MaintainGalleries.php
- app/Contracts/Web3DataProvider.php
- app/Http/Client/Alchemy/AlchemyPendingRequest.php
- app/Http/Client/Moralis/MoralisPendingRequest.php
- app/Jobs/FetchUserNfts.php
- app/Jobs/FetchWalletNfts.php
- app/Models/Wallet.php
- app/Services/Web3/Alchemy/AlchemyWeb3DataProvider.php
- app/Services/Web3/Fake/FakeWeb3DataProvider.php
- app/Services/Web3/Footprint/FootprintWeb3DataProvider.php
- app/Services/Web3/Mnemonic/MnemonicWeb3DataProvider.php
- app/Services/Web3/Moralis/MoralisWeb3DataProvider.php
- app/Support/Facades/Alchemy.php
- app/Support/Facades/Moralis.php
- app/Support/Web3NftHandler.php
- database/seeders/LiveUserSeeder.php
- tests/App/Http/Client/Alchemy/AlchemyPendingRequestTest.php
- tests/App/Jobs/FetchUserNftsTest.php
- tests/App/Jobs/FetchWalletNftsTest.php
- tests/App/Services/Web3/Alchemy/AlchemyWeb3DataProviderTest.php
- tests/App/Services/Web3/Fake/FakeWeb3DataProviderTest.php
- tests/App/Services/Web3/Footprint/FootprintWeb3DataProviderTest.php
- tests/App/Services/Web3/Mnemonic/MnemonicWeb3DataProviderTest.php
- tests/App/Services/Web3/Moralis/MoralisWeb3DataProviderTest.php
- tests/App/Support/Web3NftHandlerTest.php
https://app.clickup.com/t/862kd85zc
> refactor: use wallet and network models when retrieving wallet NFTs

- resources/js/Pages/Collections/Index.tsx
Closes https://app.clickup.com/t/8678v7q4k
> fix: reset page when changing visibility status in collections

- resources/js/Components/Layout/AuthOverlay/AuthOverlay.blocks.tsx
- resources/js/Components/Layout/Overlay/Overlay.blocks.tsx
https://app.clickup.com/t/862kdu59c
> refactor: center "waiting for signature" text

- app/Providers/AuthServiceProvider.php
https://app.clickup.com/t/8678vgv44
> fix: set testing wallet as signed in testing_e2e

- resources/js/Pages/Collections/Hooks/useCollections.ts
Closes https://app.clickup.com/t/8678vhqay
> fix: provide default stats in collections hook

- resources/js/Components/Collections/CollectionActions/CollectionActions.test.tsx
- resources/js/Components/Collections/CollectionActions/CollectionActions.tsx
- resources/js/Components/Collections/CollectionCard/CollectionCard.test.tsx
- resources/js/Components/Collections/CollectionsGrid/CollectionsGrid.test.tsx
- resources/js/Components/Collections/CollectionsTable/CollectionsTable.test.tsx
- Signature is now required when trying to report a collection in its overview page `/collections`.
https://github.com/ArdentHQ/dashbrd/assets/55117912/b67b8c1f-3571-43e3-a1b8-7f6794ca434e
- Initialize the app in `local` mode.
- Run `composer db:dev`, and make sure you have your Metamask wallet assigned to `LOCAL_TESTING_ADDRESS` env var.
- Now run `pnpm dev` and wait for the app to load correctly.
- Go to `/collections` page.
- Click on the three dots to see the collection actions. 
- Try to report a collection without signing your wallet and see the magic ✨ 
-   [ ] I checked my (code) changes for obvious issues, debug statements and …
> fix: require signature for reporting on collections overview page

- resources/js/Components/Collections/CollectionActions/CollectionActions.test.tsx
- resources/js/Components/Collections/CollectionCard/CollectionCard.test.tsx
- resources/js/Components/Collections/CollectionHeader/CollectionHeaderTop.test.tsx
- resources/js/Components/Collections/CollectionsGrid/CollectionsGrid.test.tsx
- resources/js/Components/Collections/CollectionsTable/CollectionsTable.test.tsx
- resources/js/Components/Galleries/GalleryPage/GalleryControls.test.tsx
- resources/js/Components/Galleries/GalleryPage/GalleryReportModal.test.tsx
- resources/js/Components/Galleries/NftGalleryCard.blocks.test.tsx
- resources/js/Components/Report.test.tsx
- resources/js/Hooks/useAuthorizedAction.test.ts
- resources/js/Hooks/useAuthorizedAction.ts
- resources/js/Pages/Galleries/Index.tsx
- resources/js/Pages/Galleries/MyGalleries/Create.tsx
- resources/js/Pages/Galleries/MyGalleries/Index.tsx
- routes/web.php
- tests/App/Http/Controllers/MyGalleryControllerTest.php
Closes https://app.clickup.com/t/862kef1nm
> refactor: ask for signature when publishing gallery

- resources/js/Components/Collections/Nfts/NftHeader/NftBasicInfo.test.tsx
https://app.clickup.com/t/8678whdgy
> fix: always create collection with image for nftbasicinfo test

- stories/Documentation/Color.tsx
https://app.clickup.com/t/8678whfw6
> fix: storybook missing hint colors

- resources/js/Components/Layout/Footer.tsx
- `Footer` component has been refactored to support our new footer design for mobile and tablet views.
- As part of the refactor, we now have two child components for the user named `SocialIcons` and `PoweredBy`, to make the code look cleaner.
- Class names for the social icon buttons have been updated to match the design.
1. Run the app in `local` or `test_e2e` mode.
2. Navigate to any page.
3. Scroll down until you reach the bottom of the page and see the magic ✨ 
- 320:
- 375:
- 640:
- 768:
- 960:
- 1024:
- 1280:
- 1440:
-   [ ] I opened a …
> refactor: new footer design for tablet and mobile views

- resources/css/_buttons.css
- resources/css/_general.css
- resources/js/Components/Collections/CollectionDescription/CollectionDescription.tsx
- resources/js/Components/ConfirmationDialog.tsx
- resources/js/Components/Dialog.tsx
- resources/js/Components/EmptyBlock/EmptyBlock.tsx
- resources/js/Components/Form/Checkbox.tsx
- resources/js/Components/Form/Radio.tsx
- resources/js/Components/Form/SearchInput.tsx
- resources/js/Components/Form/TextInput/TextInput.styles.ts
- resources/js/Components/Form/TextInput/TextInput.tsx
- resources/js/Components/Form/Toggle.tsx
- resources/js/Components/Form/__snapshots__/Toggle.test.tsx.snap
- resources/js/Pages/Collections/Components/CollectionPropertiesFilter/CollectionPropertiesFilter.blocks.tsx
- resources/js/Pages/Collections/Components/CollectionPropertiesFilter/CollectionPropertiesFilter.tsx
- Dark mode class names have been set for the following components:
- Toggle
- Checkbox
- Text Input
- Search Input
- Radio Input
- In addition, some classes were updated to match the styles for buttons in dark mode.
- Report modal and collection filters have also been updated to support dark mode.
- Run the app in `local` or `testing_e2e` mode.
- Go to `/settings` page.
- Turn dark mode on and see the magic ✨ 
-   [ ] I added a short description on how to test this PR …
> feat: dark mode for toggles, checkbox, text & radio inputs

- app/Support/Web3NftHandler.php
https://app.clickup.com/t/85zu2cvgr
> fix: skip collection value update if no user is affected to prevent deadlock

- app/Console/Commands/FetchCollectionBannerBatch.php
- tests/App/Console/Commands/FetchCollectionBannerBatchTest.php
https://app.clickup.com/t/862kf4vnv
> fix: ambiguous ID reference with FetchCollectionsBannerBatch

- app/Console/Commands/FetchCollectionBannerBatch.php
- app/Http/Controllers/MyGalleryController.php
- app/Models/Gallery.php
- database/migrations/2023_09_22_145935_update_prune_galleries_trigger.php
- database/migrations/2023_10_02_220405_add_deleted_at_column_to_gallery_nfts.php
- database/migrations/2023_10_02_223941_add_deleted_at_to_galleries_table.php
- database/migrations/2023_10_02_230839_create_recover_galleries_nfts_trigger.php
- database/migrations/2023_10_02_230839_create_recover_galleries_trigger.php
- queries/migrations.create_prune_galleries_trigger.sql
- queries/migrations.create_recover_galleries_nfts_trigger.sql
- queries/migrations.create_recover_galleries_trigger.sql
- tests/App/Console/Commands/FetchCollectionBannerBatchTest.php
- tests/App/Jobs/FetchWalletNftsTest.php
- tests/App/Models/GalleryTest.php
> chore: merge rc into main

- tests/App/Models/WalletTest.php
Closes https://app.clickup.com/t/862kfpv0a
> fix: flaky wallet test

- database/migrations/2023_09_07_135157_add_token_number_column_to_nft_activity_table.php
> fix: add `typeNumeric` macro to migrations

- app/Data/Articles/ArticleData.php
- app/Filament/Resources/ArticleResource.php
- app/Http/Controllers/ArticleController.php
- app/Models/Article.php
- database/seeders/ArticleSeeder.php
- tests/App/Http/Controllers/ArticleControllerTest.php
Closes https://app.clickup.com/t/8678v0cyu
For the moment i added a conversion for the cover image used on the article view page and the meta page, we should add more conversions for the different sizes but since those images are responsive think it requires some discussion so it can be handled as another task, created a ticket for that -->  https://app.clickup.com/t/865d7nd1u
-   [ ] I added a …
> feat: article cover image

- app/Data/Articles/FeaturedCollectionData.php
- app/Models/Article.php
https://app.clickup.com/t/862kfvnnx
> fix: featured articles images

- app/Models/Collection.php
- database/migrations/2023_09_07_135157_add_token_number_column_to_nft_activity_table.php
Closes: https://app.clickup.com/t/862kg19mw
> perf: improve collections sorting speed

- app/Http/Controllers/CollectionController.php
- resources/js/Components/Collections/CollectionActivityTable/CollectionActivityTable.test.tsx
- resources/js/Components/Collections/CollectionActivityTable/CollectionActivityTable.tsx
- resources/js/Pages/Collections/Components/CollectionNavigation/CollectionNavigation.tsx
- resources/js/Pages/Collections/View.tsx
https://app.clickup.com/t/862kftp7w
> refactor: enable collection activity tab

- resources/js/Components/Collections/CollectionActivityTable/CollectionActivityTable.blocks.tsx
https://app.clickup.com/t/862kg76e9
> fix: activity table nft name size on mobile

- app/Http/Client/Alchemy/AlchemyPendingRequest.php
- tests/App/Http/Client/Alchemy/AlchemyPendingRequestTest.php
- tests/fixtures/alchemy/nfts_array_collection_array_traits.json
- tests/fixtures/alchemy/nfts_array_unexpected_traits.json
https://app.clickup.com/t/862kgayr2
> fix: handle unexpected trait formats better

- resources/js/Pages/Collections/Components/CollectionNavigation/CollectionNavigation.tsx
Closes: https://app.clickup.com/t/862kfvtqf
Design: https://www.figma.com/file/2Rr7zzoeGGiHYsROvfHaGe/Dashboard?node-id=22708%3A143147&mode=dev
-   [x] I checked my UI changes against the design and there are no notable differences
-   [x] I checked my UI changes for any responsiveness issues
> refactor: make collection navigation a dropdown in mobile view

- resources/js/Pages/Collections/Components/CollectionsHeading/CollectionsHeading.tsx
Closes: https://app.clickup.com/t/86790e9wg
> fix: collections page header

- app/Filament/Resources/UserResource.php
https://app.clickup.com/t/862kh3mqh
> fix: use username for displayname in filament

- resources/js/Pages/Articles/Show.tsx
https://app.clickup.com/t/862kh3jb0
> fix: make the border 1px on the article details page

- resources/js/Components/Articles/ArticleCard/ArticleCard.tsx
- resources/js/Pages/Articles/Components/HighlightedArticles.tsx
https://app.clickup.com/t/862kh3jfw
> refactor: handle no overflow scenario in article card titles

- app/Filament/Resources/ArticleResource.php
https://app.clickup.com/t/862kh447a
> refactor: truncate long article title in admin panel

- resources/js/Components/FeaturedCollectionsBanner/FeaturedCollectionsBanner.tsx
https://app.clickup.com/t/862kh49a7
> fix: background color on the featured collections card

- resources/js/Components/Articles/ArticleCard/ArticleCard.tsx
https://app.clickup.com/t/862kh6bde
> refactor: highlighted article headline color

- resources/js/Components/Layout/LayoutWrapper.tsx
- resources/js/Components/Layout/Navbar.tsx
- resources/js/Pages/Settings/Layout.tsx
https://app.clickup.com/t/862kh4zjt
> refactor: navbar width

- resources/css/_article.css
adjusts font size and padding to improve readability of articles
> refactor: article content padding adjustments

- resources/css/_article.css
https://app.clickup.com/t/862kh7c0j
> refactor: more padding adjustments for article content

- resources/js/Components/Collections/CollectionDescription/CollectionDescription.tsx
https://app.clickup.com/t/862kh77t9
> fix: "about nft" modal title

- resources/css/_article.css
https://app.clickup.com/t/862kh7c0j blockquote adjustments
> refactor: adjust article blockquote styling

- resources/css/_article.css
- resources/js/Pages/Collections/Components/Articles/ArticlesScroll.tsx
Closes https://app.clickup.com/t/862kh81bj
> fix: make all article slider cards same height

- resources/css/_article.css
https://app.clickup.com/t/862kh7c0j
> refactor: adjust article heading padding

- resources/js/Components/Collections/Nfts/NftHeader/NftBasicInfo.tsx
- resources/js/Components/Galleries/GalleryPage/GalleryNftsNft.tsx
fixup https://github.com/ArdentHQ/dashbrd/pull/290
Part of https://app.clickup.com/t/861nbbrbz
> fix: correct image dimensions in nft & gallery page

- resources/types/generated.d.ts
fix outdated generated types file introduced by https://github.com/ArdentHQ/dashbrd/pull/302
> chore: update generated types file

- resources/js/Pages/Articles/Components/WaveSurferPlayer.tsx
- `WaveSurferPlayer` component has been refactored and it now matches new mobile design from our Figma.
- Dark mode has been enabled for this component, too.
- Make sure you have the migrations for this branch using `composer db:dev`.
- Also, go to your `DB` and in `articles` table, set `https://dashbrd-testing.s3.eu-west-1.amazonaws.com/24/en.0199216d-8e1d-419c-b207-e8c0a611f969.mp3` for `audio_file_url` in any article you want to test.
- Run the app in `local` or `testing_e2e` mode.
- Go to `/articles`.
- Click on the article you set the audio file for and see the magic ✨ 
## Screenshots
- Dark mode:
- Light mode:
- …
> feat: new mobile version and dark mode for WebSurferPlayer

- routes/api.php
> fix: do not require authentication when viewing galleries

- resources/js/Components/Galleries/GalleryPage/GalleryActionToolbar/GalleryActionToolbar.tsx
- resources/types/generated.d.ts
Closes https://app.clickup.com/t/862khu5c1
> fix: show thumbnail in gallery form cover image button

- resources/js/Components/Articles/Article.blocks.tsx
Closes https://app.clickup.com/t/862khvm7d
> fix: correct dimensions in article feature collection avatars

- resources/css/_buttons.css
- resources/js/Components/Tokens/TokenLogo.tsx
Closes https://app.clickup.com/t/862khvpc1
> fix: dark wallet issues

- resources/css/_skeletons.css
- resources/js/Pages/Galleries/Components/GalleryListbox/GalleryListbox.tsx
Closes https://app.clickup.com/t/862khyu14
> fix: correct skeleton colors in dark mode

- resources/js/Components/Galleries/NftGalleryCardEditable.tsx
https://app.clickup.com/t/862kj49hq
> refactor: nft gallery card styling

- resources/js/Pages/Collections/Components/CollectionsFilter/CollectionsFilterPopover.tsx
Closes https://app.clickup.com/t/860ryz1dv
> fix: collection applied filter indicator in dark mode

- resources/js/Components/BalanceHeader/BalanceHeader.tsx
Closes https://app.clickup.com/t/860ryz129
> fix: wallet balance separator dark color

- resources/js/Components/Drafts/NftDraftCard.blocks.tsx
Closes https://app.clickup.com/t/86dqha6cr
> fix: adjust size of draft delete icon button

- resources/js/Components/Sidebar/SidebarItem.tsx
https://app.clickup.com/t/86dqha6e7
> fix: remove transition from sidebar items

- resources/js/Components/Image/Image.tsx
Closes https://app.clickup.com/t/86dqha6mr
> fix: correct size for errored image placeholder

- resources/css/_buttons.css
- resources/js/Components/Tokens/TokenLinks.tsx
Closes https://app.clickup.com/t/86dqha7fq
> fix: icon button hover color on dark mode

- resources/js/Pages/Galleries/MyGalleries/Index.tsx
Closes https://app.clickup.com/t/86dqha7cn
> fix: my galleries empty block text color on dark mode

- resources/js/Components/Navbar/UserDetails.tsx
Closes https://app.clickup.com/t/86dqha77e
> fix: user details label text color 

- resources/js/Pages/Collections/Components/CollectionsHeading/RefreshButton.tsx
Closes https://app.clickup.com/t/86dqha73b
> fix: refresh collections tooltip dark colors

- resources/js/Components/Heading.tsx
- resources/js/Components/__snapshots__/Heading.test.tsx.snap
- resources/js/Pages/Articles/Show.tsx
Closes https://app.clickup.com/t/862kh3k35
> fix: break words on articles

- resources/js/Components/Form/Listbox/Listbox.blocks.tsx
- Dark mode styles has been fixed for `hover` and `selected` states when using `Listbox` component.
## Screenshots:
- Pagination component (implements Listbox):
- Dropdown input (implements Listbox):
2. Make sure your testing wallet has multiple tokens and NFTs.
3. Go to `My wallet` button in your account dropdown from the navbar.
4. Click on `Send` button.
5. Open the token dropdown and see the magic ✨ 
-   [ ] I opened a corresponding card on Clickup for any remaining TODOs in my …
> fix: selected and hover styles for listbox dark mode

- app/Filament/Resources/ArticleResource.php
Closes https://app.clickup.com/t/86dqha6fj
> fix: validate articles banner max size

- resources/js/Components/Articles/ArticleCard/ArticleCard.tsx
- resources/js/Components/Articles/ArticleListItem/ArticleListItem.tsx
- resources/js/Pages/Collections/Components/Articles/ArticlesList.tsx
Closes https://app.clickup.com/t/86dqha71v
> fix: missing hover state articles list item

- resources/js/Components/Tokens/TokenLogo.tsx
- resources/js/Components/TransactionFormSlider/Components/SearchAssets/SearchAssets.tsx
- resources/js/Components/TransactionFormSlider/Components/SelectAsset/SelectAsset.blocks.tsx
Closes https://app.clickup.com/t/86dqha6ee 
> fix: correct badge colors for tokens

- resources/js/Pages/Articles/Components/HighlightedArticles.tsx
- resources/js/Pages/Collections/Components/Articles/ArticlesGrid.tsx
https://app.clickup.com/t/86dqhaf6y
> fix: article column responsiveness in overview page

- resources/css/app.css
- resources/js/Components/Layout/LayoutWrapper.tsx
- Custom `transition-default` class name has been added for `header` HTML tag.
2. Click on the `Dark mode toggle` and see the magic ✨ 
https://github.com/ArdentHQ/dashbrd/assets/55117912/2bcd1510-2ba3-4251-b245-2aafbd31d174
- …
> fix: transition effect for color change on dark mode toggle

- resources/js/Components/SortDropdown.tsx
https://app.clickup.com/t/86dqhafh3
> fix: article dropdown color on dark mode

- resources/js/Components/Drafts/NftGalleryDraftCard.blocks.test.tsx
- resources/js/Components/Drafts/NftGalleryDraftCard.blocks.tsx
- resources/js/Components/Drafts/NftGalleryDraftCard.test.tsx
- resources/js/Components/Drafts/NftGalleryDraftCard.tsx
- resources/js/Pages/Galleries/MyGalleries/Index.tsx
- `NftDraftCard` component has been renamed to `NftGalleryDraftCard`.
- Children components and unit tests have also been renamed.
- Implementations of these components have also been updated.
> Note: While doing this ticket, also did a quick research about the following:
>  - `GalleryCard` component: is the basic card implemented to display each NFT that a gallery contains. Also implemented to contain the NFT Image on the NFT details page.
>  - `NFTGalleryCard` component: is the card that appears on `/gallery` page. It displays the first 6 NFTs of a gallery or its banner.
>  - `NFTGalleryDraftCard` component: is the newest card implemented for this functionality. At the moment, it is just implemented on the drafts tab.
> I would just recommend making sure the implementations of this card …
> refactor: rename nft draft card

- resources/js/Pages/Articles/Components/ArticleMeta.tsx
https://app.clickup.com/t/86dqhahft
dark-700 to match other borders in the author box.
> fix: dashed border color for author box

- resources/js/Pages/Galleries/MyGalleries/Components/MyGalleryListboxMenu.tsx
https://app.clickup.com/t/86dqhahur
> fix: show number of published galleries instead of NFTs in sidebar

- resources/js/Components/Articles/ArticleListItem/ArticleListItem.tsx
https://app.clickup.com/t/86dqhbga0
> fix: break words for article title in list view

- resources/js/Components/Articles/ArticleCard/ArticleCard.tsx
Closes https://app.clickup.com/t/86dqhc0px
> refactor: article card outline on hover

- app/Filament/Resources/ArticleResource.php
https://app.clickup.com/t/86dqhc8g0
> refactor: require cover photo when creating/editing articles

- app/Http/Controllers/ArticleController.php
https://app.clickup.com/t/86dqhd5vy
Same change as in #404 
Reduces query count from 46 to 30.
> refactor: eager load media and author media when reading article

- resources/js/Contexts/DraftGalleriesContext.tsx
- resources/js/Pages/Galleries/MyGalleries/Index.tsx
- resources/js/app.tsx
This PR moves the context to be a global context
Note: I tried different options to prevent adding a global context but any of those worked, at the end the context should not add performance issues or something similar really since is mounted once when the page is loaded (or wallet changes) and only reads the local storage so think that solution is not really bad, open to discussion
Closes https://app.clickup.com/t/86dqhae56
-   [ ] I added a short description on how …
> fix: gallery count handling

- app/Models/User.php
- tests/App/Models/UserTest.php
https://app.clickup.com/t/86dqhwp1t
> fix: explicitly define admin guard when checking access permission

- resources/js/Components/Galleries/NftGalleryCard.tsx
Closes https://app.clickup.com/t/86dqjgb8m
> fix: make gallery cards clickable

- resources/js/Components/Galleries/DeleteGalleryButton.tsx
https://app.clickup.com/t/86dqjg4fv
> refactor: gallery delete button color

- resources/js/Pages/Galleries/MyGalleries/Create.tsx
Closes https://app.clickup.com/t/86dqjgcz6
> fix: auth overlay on create gallery page 

- resources/js/Pages/Galleries/hooks/useWalletDraftGallery.ts
Closes https://app.clickup.com/t/86dqjgdg4
> fix: prevent from saving draft on disabled state

- resources/js/Pages/Collections/Index.tsx
Closes: https://app.clickup.com/t/86dqjgpcj
> fix: reload collections when wallet switches

- resources/js/Pages/Galleries/MyGalleries/Create.tsx
- resources/js/Pages/Galleries/MyGalleries/Index.tsx
Closes https://app.clickup.com/t/86dqjhe2m
> fix: delete gallery not asking for signature

- resources/js/Components/Layout/AuthOverlay/AuthOverlay.blocks.tsx
- resources/js/Components/Layout/AuthOverlay/AuthOverlay.test.tsx
- resources/js/Components/Layout/AuthOverlay/AuthOverlay.tsx
Closes https://app.clickup.com/t/8678wkaep
> fix: display same sign overlay on all cases

- resources/js/Pages/Galleries/MyGalleries/Index.tsx
Closes https://app.clickup.com/t/86dqjgbzm
> fix: disconnect wallet exception on my galleries

- resources/js/Components/Drafts/NftGalleryDraftCard.blocks.test.tsx
- resources/js/Components/Drafts/NftGalleryDraftCard.blocks.tsx
https://app.clickup.com/t/86dqjt837
> refactor: show N/A when no value for draft gallery cards

- resources/js/Pages/Galleries/hooks/useWalletDraftGalleries.ts
> chore: add comment for reactivity regarding `indexedDB`

- resources/js/Components/Galleries/GalleryPage/GalleryActionToolbar/GalleryDraftDeleteButton.tsx
- resources/js/Pages/Galleries/MyGalleries/Index.tsx
https://app.clickup.com/t/86dqm0ja5
> refactor: use "success" toast when removing drafts

- app/Enums/CryptoCurrencyDecimals.php
Use `match()` instead of this `constant()` function, just to make it a bit more modern, less clunky and more verbose.
> refactor: clean up `CryptoCurrencyDecimals` enum

- app/Http/Controllers/CollectionController.php
https://app.clickup.com/t/86dqmd20n
> refactor: load collections in general instead of user specific

- app/Filament/Resources/CollectionResource.php
https://app.clickup.com/t/86dqmd23q
> refactor: display icon in admin panel when collection is featured

- phpunit.xml
fixes misconfiguration of phpunit
> fix: phpunit misconfiguration

- database/seeders/CollectionVotesSeeder.php
- database/seeders/DatabaseSeeder.php
Closes: https://app.clickup.com/t/86dqpzq4p
> feat: add collection vote seeder

- resources/js/Components/Heading.tsx
- resources/js/Pages/Collections/Components/CollectionVoting/VoteCollections.tsx
https://app.clickup.com/t/86dqqdr5p
> fix: collection of the month styling

- app/Http/Controllers/CollectionOfTheMonthController.php
Closes https://app.clickup.com/t/86dqrp2vd
> feat: add real collection of the month data on overview page

- tests/App/Http/Controllers/CollectionOfTheMonthControllerTest.php
https://app.clickup.com/t/86dqt9cxn
> fix: flaky collections of the month test

- app/Console/Commands/FetchCollectionBanner.php
- app/Console/Commands/FetchCollectionBannerBatch.php
- app/Console/Commands/FetchCollectionFloorPrice.php
- app/Console/Commands/FetchCollectionMetadata.php
- app/Console/Commands/FetchCollectionOpenseaSlug.php
- app/Console/Commands/FetchCollectionOwners.php
- app/Console/Commands/FetchCollectionTraits.php
- app/Console/Commands/FetchCollectionVolume.php
- tests/App/Console/Commands/FetchCollectionBannerBatchTest.php
- tests/App/Console/Commands/FetchCollectionBannerTest.php
- tests/App/Console/Commands/FetchCollectionFloorPriceTest.php
- tests/App/Console/Commands/FetchCollectionMetadataTest.php
- tests/App/Console/Commands/FetchCollectionOpenseaSlugTest.php
- tests/App/Console/Commands/FetchCollectionOwnersTest.php
- tests/App/Console/Commands/FetchCollectionTraitsTest.php
- tests/App/Console/Commands/FetchCollectionVolumeTest.php
https://app.clickup.com/t/86dqu7akk
...instead of `nfts:`. Something that annoyed me :trollface: 
> refactor: prefix collection-related artisan commands with `collections:`

- app/Http/Controllers/PopularCollectionController.php
- app/Models/Collection.php
- tests/App/Models/CollectionTest.php
Closes: https://app.clickup.com/t/86dqu7fb2
-   [x] I checked my (code) changes for obvious issues, debug statements and commented code
-   [x] Tests _(if necessary)_
> feat: add popular collection stats

- resources/js/Components/Galleries/GalleryPage/GalleryActionToolbar/GalleryActionToolbar.test.tsx
> fix: warnings in tests

- app/Data/Collections/CollectionFeaturedData.php
- app/Filament/Resources/CollectionResource.php
- app/Http/Controllers/CollectionController.php
- tests/App/Http/Controllers/CollectionControllerTest.php
https://app.clickup.com/t/86dqv2y6p
From **77** queries and **253** models to **32** queries and **223** models.
> refactor: cut the number of queries in featured collections

- app/Data/Collections/VotableCollectionData.php
Closes https://app.clickup.com/t/86dqxn54n
The ticket says that the modal share button does not work but it works for me in the sense that it opens twitter, what is wrong is that is using the whole twitter url instead of the handling when sharing `I voted for @https://x.com/user` instead of `I voted for @user` which I suspect in some causes may broke the link
This pr fixed the handle issue and probably other issues as well @samharperpittam 
-   [ ] I added a short …
> fix: share on twitter modal handle issue

- resources/views/app.blade.php
https://app.clickup.com/t/86dr3h2np
> fix: remove visible transition from light to dark mode on page load

- app/Models/CollectionWinner.php
- resources/js/Pages/Collections/CollectionOfTheMonth.tsx
https://app.clickup.com/t/86dr3h27h
> fix: collection of the month error

- resources/js/Pages/Collections/Components/CollectionVoting/VoteCountdown.tsx
https://app.clickup.com/t/86dr5agmb
Looks prettier.
> refactor: change the font weight on "Time left" label

- resources/js/Components/Collections/CollectionOfTheMonthWinners/CollectionOfTheMonthWinners.blocks.tsx
https://app.clickup.com/t/86dr5aw2g
> refactor: ensure winner avatars are clickable on the "collection of the month" page

- resources/js/Components/Collections/CollectionOfTheMonthWinners/CollectionOfTheMonthWinners.blocks.tsx
- resources/js/Pages/Collections/Components/CollectionVoting/VoteCollections.tsx
- resources/js/Pages/Collections/Index.tsx
https://app.clickup.com/t/86dr5dac2
When testing, please check all breakpoints.
> fix: place "previous winners" In a "vote for cotm" block

- app/Http/Controllers/CollectionVoteController.php
- tests/App/Http/Controllers/CollectionVoteControllerTest.php
https://app.clickup.com/t/86dr5wcna
> fix: change voting limit to once a month instead of 30 days

- resources/js/Components/Collections/CollectionsFullTable/CollectionName.tsx
- resources/js/Components/Collections/CollectionsFullTable/CollectionsFullTableItem.tsx
https://app.clickup.com/t/86dr6q06p
> fix: increase name column width on the popular collection table

- app/Filament/Resources/CollectionResource.php
https://app.clickup.com/t/86dr8g6ze
> refactor: prevent collections with no NFTs from being set as featured

- resources/js/Pages/Collections/Components/CollectionVoting/VoteCollections.tsx
https://app.clickup.com/t/86dr8h8b4
Plus, `div` is not a valid `button` child.
> refactor: use `button` element for collection row when voting

- app/Http/Controllers/CollectionController.php
- app/Http/Controllers/PopularCollectionController.php
- app/Models/Traits/HasVolume.php
- tests/App/Models/CollectionTest.php
https://app.clickup.com/t/86dracfvc
> refactor: sort collections by volume fiat value

- resources/js/Pages/Collections/Index.tsx
https://app.clickup.com/t/86drafz80
> refactor: hide articles section if none have been published

- app/Http/Controllers/CollectionController.php
- resources/js/Pages/Collections/Components/FeaturedCollections/FeaturedCollectionsCarousel.tsx
- resources/js/Pages/Collections/Index.tsx
https://app.clickup.com/t/86dratuhy
> refactor: hide featured collections if there are none

- resources/js/Pages/Collections/Components/CollectionsArticles.tsx
https://app.clickup.com/t/86draf2bf
> refactor: show the article placeholder if there's only a few articles

- app/Http/Controllers/CollectionVoteController.php
- tests/App/Http/Controllers/CollectionVoteControllerTest.php
https://app.clickup.com/t/86drb881e
> fix: allow second/third ranked "cotm" collections to be voted on

- resources/js/Pages/Collections/Components/CollectionsHeading/CollectionsHeading.tsx
https://app.clickup.com/t/86drc9bz3
> refactor: format the number of NFTs and collections on the "popular collections" page

- app/Http/Controllers/CollectionController.php
- app/Models/Traits/HasVolume.php
- database/migrations/2024_01_29_161909_add_index_to_tokens_table.php
https://app.clickup.com/t/86drc7q7m
> refactor: improve `JOIN` query

- app/Console/Commands/UpdateArticlesViewCount.php
- app/Http/Controllers/CollectionController.php
- app/Observers/ArticleObserver.php
- app/Repositories/ArticleRepository.php
- tests/App/Observers/ArticleObserverTest.php
https://app.clickup.com/t/86drcpje0
> refactor: cache the articles on the homepage

- app/Http/Controllers/Api/PopularCollectionController.php
- app/Http/Controllers/CollectionController.php
- app/Http/Requests/FilterableCollectionRequest.php
- resources/js/Components/Collections/PopularCollectionsTable/PopularCollectionsTable.contract.ts
- resources/js/Components/Collections/PopularCollectionsTable/PopularCollectionsTable.test.tsx
- resources/js/Components/Collections/PopularCollectionsTable/PopularCollectionsTable.tsx
- resources/js/Components/Collections/PopularCollectionsTable/PopularCollectionsTableItem.tsx
- resources/js/Pages/Collections/Index.tsx
- resources/js/Pages/Collections/PopularCollections.tsx
- resources/js/Pages/Collections/ViewAllButton.tsx
- routes/api.php
- tests/App/Http/Controllers/Api/PopularCollectionControllerTest.php
https://app.clickup.com/t/86drd3umz
> refactor: lazy load popular collections on the homepage

- resources/js/Components/Collections/CollectionOfTheMonthWinners/CollectionOfTheMonthWinners.tsx
https://app.clickup.com/t/86drd3uhb
> fix: capitalize the month name properly

- app/Http/Controllers/Auth/AuthenticatedSessionController.php
- app/Http/Controllers/DashboardController.php
- app/Http/Controllers/Filament/LogoutController.php
- app/Http/Middleware/Authenticate.php
- app/Http/Middleware/ValidateWallet.php
- resources/js/Components/Layout/Navbar.tsx
- routes/web.php
- tests/App/Http/Controllers/AuthenticatedSessionControllerTest.php
- tests/App/Http/Controllers/DashboardControllerTest.php
- tests/App/Http/Controllers/Filament/LogoutControllerTest.php
- tests/App/Http/Controllers/TokenControllerTest.php
https://app.clickup.com/t/86dr9xpny
> refactor: set "collections" page as root

- app/Http/Controllers/Api/VotableCollectionController.php
- app/Http/Controllers/CollectionController.php
- resources/js/Components/Collections/PopularCollectionsTable/PopularCollectionsTableItem.tsx
- resources/js/Pages/Collections/Components/CollectionVoting/NominationDialog.tsx
- resources/js/Pages/Collections/Components/CollectionVoting/VoteCollections.test.tsx
- resources/js/Pages/Collections/Components/CollectionVoting/VoteCollections.tsx
- resources/js/Pages/Collections/Components/CollectionsVoteReceivedModal/CollectionsVoteReceivedModal.tsx
- resources/js/Pages/Collections/Index.tsx
- resources/js/utils/range.test.ts
- resources/js/utils/range.ts
- routes/api.php
- tests/App/Http/Controllers/Api/VotableCollectionControllerTest.php
- tests/App/Http/Controllers/CollectionControllerTest.php
- tsconfig.json
https://app.clickup.com/t/86drd6r32
> refactor: lazy load votable collections

- resources/css/_collection.css
https://app.clickup.com/t/86drd4vbg
> fix: shadow opacity

- resources/js/Pages/Collections/CollectionOfTheMonth.tsx
- resources/js/Pages/Collections/Components/WinnerCollections/Hooks/useWinnerCollections.ts
https://app.clickup.com/t/86drdtdk6
> fix: "cotm" winners not shown if latest month winners are equal to current month

- resources/js/Pages/Collections/CollectionsCatalog/Index.tsx
https://app.clickup.com/t/86drez3cv
> fix: update volume header in popular collections table when changing period

- resources/js/Pages/Collections/PopularCollections.tsx
https://app.clickup.com/t/86drfv907
> fix: update volume header on both popular collections tables

- app/Http/Client/Opensea/OpenseaPendingRequest.php
- tests/App/Http/Client/Opensea/OpenseaPendingRequestTest.php
- tests/App/Jobs/FetchCollectionFloorPriceTest.php
- tests/App/Services/Web3/Opensea/OpenseaWeb3DataProviderTest.php
- tests/fixtures/opensea/collection_stats.json
- tests/fixtures/opensea/collection_stats_floor_price_null.json
https://app.clickup.com/t/86drfv9p1
> refactor: use v2 of opensea api

- app/Http/Controllers/Api/VotableCollectionController.php
- app/Models/Collection.php
https://app.clickup.com/t/86drg9fb9
> fix: "division by zero" when searching for collections to nominate

- phpunit.xml
- resources/js/Components/Layout/Footer.tsx
- resources/js/Components/PoweredByIcons.tsx
https://app.clickup.com/t/86drj8qa3
> refactor: make the Footer component more React-y

- resources/js/Components/Point.tsx
https://app.clickup.com/t/86drj8p7u
This component accepts `width`, `height` and `color` (which dynamically generates Tailwind class - big no no). We don't ever use these props, so we can safely remove them.
> refactor: remove unused props from the `Point` component

- database/seeders/NftSeeder.php
https://app.clickup.com/t/86drve24r
> fix: remove `nfts_count` from nft seeder

- app/Support/Web3NftHandler.php
- tests/App/Support/Web3NftHandlerTest.php
https://app.clickup.com/t/86drw8atx
> refactor: do not fire collection jobs for erc1155 collections

- app/Http/Client/Opensea/OpenseaPendingRequest.php
- tests/App/Http/Client/Opensea/OpenseaPendingRequestTest.php
- tests/App/Jobs/FetchCollectionSupplyFromOpenSeaTest.php
https://app.clickup.com/t/86drw8avh
> fix: do not throw exception for opensea's 400 status code

- app/Jobs/FetchCollectionFloorPrice.php
- tests/App/Jobs/FetchCollectionFloorPriceTest.php
> fix: do not run job to fetch floor price if collection is missing

- app/Console/Commands/CalculateCollectionTraitRarities.php
- app/Jobs/CalculateTraitRarities.php
- app/Jobs/CalculateTraitRaritiesForCollection.php
- tests/App/Console/Commands/CalculateCollectionTraitRaritiesTest.php
- tests/App/Jobs/CalculateTraitRaritiesTest.php
```
$ php artisan collections:calculate-trait-rarities --start=1 --limit=5
Starting from ID: 9 to ID 25 collections (inclusive). Total: 3
```
```
$ php artisan collections:calculate-trait-rarities --start=1
Starting from ID: 9 to ID 55 collections (inclusive). Total: 23
```
```
$ php artisan collections:calculate-trait-rarities --collection-id=9
```
-   [ ] I added a storybook entry for the …
> refactor: add the batch options when updating collection traits

- app/Jobs/DetermineCollectionMintingDate.php
- tests/App/Jobs/DetermineCollectionMintingDateTest.php
This job runs when new collections are created. However, it can definitely happen that multiple wallets own NFTs from the same collection, and we don't want to run the job multiple times for the same collection.
> refactor: add `ShouldBeUnique` to job

- resources/js/Pages/Collections/Components/CollectionPropertiesFilter/CollectionPropertiesFilter.blocks.tsx
- resources/js/Pages/Collections/Components/CollectionPropertiesFilter/CollectionPropertiesFilter.tsx
https://app.clickup.com/t/86drvvcgn
We do some hacks around transitions to have this animated, but it just looks janky. With this PR, it'll use Accordion component from Radix to have a smoother transition.
https://github.com/ArdentHQ/dashbrd/assets/6536260/4ac4995c-0ef1-4ff5-a74b-358eb6b080de
https://github.com/ArdentHQ/dashbrd/assets/6536260/94c698bb-6f07-423d-8eab-1e124378d765
-   [ ] I added …
> refactor: use radix-ui accordion for collection traits panel

- resources/js/Components/Collections/PopularCollectionsTable/PopularCollectionsTable.test.tsx
https://app.clickup.com/t/86dt1dmbb
> fix: `tr` within `div` inside test

- resources/js/Components/Collections/CollectionPortfolioValue/CollectionPortfolioValue.test.tsx
- resources/js/Components/Collections/CollectionsTable/CollectionsTable.test.tsx
https://app.clickup.com/t/86dt1dn4r
> fix: missing test coverage

- app/Console/Commands/LiveDumpWallets.php
- app/Enums/Chain.php
- app/Enums/MnemonicChain.php
- app/Http/Client/Mnemonic/MnemonicPendingRequest.php
- app/Jobs/FetchBurnActivity.php
- app/Jobs/FetchCollectionActivity.php
- app/Jobs/FetchCollectionBanner.php
- app/Jobs/FetchCollectionVolume.php
- app/Jobs/FetchCollectionVolumeHistory.php
- app/Listeners/DispatchJobsForNewCollections.php
- app/Models/TokenPriceHistory.php
- tests/App/Console/Commands/LiveDumpWalletsTest.php
- tests/App/Enums/ChainTest.php
- tests/App/Enums/MnemonicChainTest.php
- tests/App/Http/Client/Mnemonic/MnemonicPendingRequestTest.php
- tests/App/Jobs/FetchBurnActivityTest.php
- tests/App/Jobs/FetchCollectionActivityTest.php
- tests/App/Jobs/FetchCollectionBannerTest.php
- tests/App/Jobs/FetchCollectionVolumeHistoryTest.php
- tests/App/Jobs/FetchCollectionVolumeTest.php
- tests/App/Services/Web3/Mnemonic/MnemonicWeb3DataProviderTest.php
- tests/App/Support/Facades/MnemonicTest.php
- tests/App/Support/Web3NftHandlerTest.php
https://app.clickup.com/t/86dt8452w
> refactor: disable polygon integration in mnemonic

- .gitignore
- app/Console/Commands/LiveDumpWallets.php
- app/Enums/Chain.php
- app/Enums/MnemonicChain.php
- app/Http/Client/Mnemonic/MnemonicPendingRequest.php
- app/Jobs/FetchBurnActivity.php
- app/Jobs/FetchCollectionActivity.php
- app/Jobs/FetchCollectionBanner.php
- app/Jobs/FetchCollectionVolume.php
- app/Jobs/FetchCollectionVolumeHistory.php
- app/Listeners/DispatchJobsForNewCollections.php
- app/Models/TokenPriceHistory.php
- resources/js/Components/Collections/CollectionPortfolioValue/CollectionPortfolioValue.test.tsx
- resources/js/Components/Collections/CollectionsTable/CollectionsTable.test.tsx
- resources/js/Components/Collections/PopularCollectionsTable/PopularCollectionsTable.test.tsx
- resources/js/Pages/Collections/Components/CollectionPropertiesFilter/CollectionPropertiesFilter.blocks.tsx
- resources/js/Pages/Collections/Components/CollectionPropertiesFilter/CollectionPropertiesFilter.tsx
- tests/App/Console/Commands/LiveDumpWalletsTest.php
- tests/App/Enums/ChainTest.php
- tests/App/Enums/MnemonicChainTest.php
- tests/App/Http/Client/Mnemonic/MnemonicPendingRequestTest.php
- tests/App/Jobs/FetchBurnActivityTest.php
- tests/App/Jobs/FetchCollectionActivityTest.php
- tests/App/Jobs/FetchCollectionBannerTest.php
- tests/App/Jobs/FetchCollectionVolumeHistoryTest.php
- tests/App/Jobs/FetchCollectionVolumeTest.php
- tests/App/Services/Web3/Mnemonic/MnemonicWeb3DataProviderTest.php
- tests/App/Support/Facades/MnemonicTest.php
- tests/App/Support/Web3NftHandlerTest.php
> chore: merge develop into main
