ArdentHQ/dashbrd

resources/js/Pages/Collections/View.tsx
fix for https://github.com/ArdentHQ/dashbrd/pull/48
=> fix: hide collection nfts when toggled and 0 owned

resources/js/Components/Collections/Nfts/NftReportModal/NftReportModal.tsx, routes/web.php
- When users reported an NFT, we were using the `tokenNumber` of an NFT, which sometimes was duplicated and caused the admin to go to a different NFT to see the report.
- To solve this, we're now using the NFT `id` property.
1. Follow the steps in the video to see the magic 🌟 
https://github.com/ArdentHQ/dashbrd/assets/55117912/a652c9c8-1014-4c89-adf3-bddc889e834e
-   [ ] I added a storybook …
=> fix: incorrect nft being reported

app/Jobs/DetermineCollectionMintingDate.php
Closes https://app.clickup.com/t/85ztyf16c
Issue was because the test uses two collections, the one without minted date and another with minted date, the query used to search for a collection and sometimes it returned the one that it was supposed to be updated (probably because both have the same created date, adding an extra query param solved the issue and the potential logic error
-   [ ] I …
=> fix: flaky test, collections with minted_date

config/debugbar.php
Views is mostly irrelevant as we use Inertia and React. Gates we don't use except for the admin panel. Livewire we don't use.
=> chore: disable views, gate and livewire tabs for debugbar

app/Http/Controllers/CollectionController.php, app/Models/Collection.php, resources/js/Pages/Collections/Index.tsx, tests/App/Models/CollectionTest.php
- Collections are now sorted by name in `asc` order.
- New tests have been added for these changes.
=> feat: sort collections by name in asc order by default

app/Http/Controllers/CollectionController.php, app/Models/Collection.php, tests/App/Models/CollectionTest.php
This reverts commit 6f26bac7b2b507415c06840b5c32a6d496f45356.
Revert #163 to avoid slow sorting on pageload
=> Revert "feat: sort collections by name in asc order by default (#163)"

resources/js/Components/Layout/AuthOverlay/AuthOverlay.blocks.tsx
- `Back` button behavior has been fixed when trying to access `Settings` page.
- Width for the button in small mobile screens has been fixed, too.
1. Run the app in `local` mode.
2. Connect your wallet and make sure you haven't signed anything.
3. Try to perform an action that requires a signature (for example, report a gallery).
4. Once the signature modal appears, open the user dropdown.
5. Click in `Settings` and see the magic ✨ 
https://github.com/ArdentHQ/dashbrd/assets/55117912/b8d62029-cde9-426a-97b1-9a1d0d6fdfc1
-   [ ] I opened a …
=> fix: back button behavior for settings page

app/Http/Controllers/MyGalleryController.php, app/Models/Gallery.php, database/migrations/2023_09_22_145935_update_prune_galleries_trigger.php, database/migrations/2023_10_02_220405_add_deleted_at_column_to_gallery_nfts.php, database/migrations/2023_10_02_223941_add_deleted_at_to_galleries_table.php, database/migrations/2023_10_02_230839_create_recover_galleries_nfts_trigger.php, database/migrations/2023_10_02_230839_create_recover_galleries_trigger.php, queries/migrations.create_prune_galleries_trigger.sql, queries/migrations.create_recover_galleries_nfts_trigger.sql, queries/migrations.create_recover_galleries_trigger.sql, tests/App/Jobs/FetchWalletNftsTest.php, tests/App/Models/GalleryTest.php
There is not really easy to test so a careful analysis to the querys is goint to be necessary
Whats expected is the following:
1. When a gallery nft is unassigned from a wallet (no longer belong to wallet) is soft deleted from the gallery and should not appear in the gallery view page
2. if a nft is assigned again it appears in the gallery again
3. if all nfts from the gallery are unassigned the gallery is also soft delted
4. if the nft belongs to the gallery again the gallery is recovered with that nft
5. if the nft changes to another owner is completely removed from the gallery
6. if all nfts are completely removed from a gallery the gallery is also completely removed
https://app.clickup.com/t/8678u37n1
-   [ ] I checked my UI changes against the design and there are no notable …
=> refactor: soft delete gallery nfts

database/seeders/AdminUserSeeder.php
sets `password` as password for local environment when seeding
=> chore: use "password" password for filament in local env

resources/js/Components/Navbar/MobileMenu.tsx, resources/js/Components/Navbar/UserDetails.tsx
# [[navbar] user dropdown light mode UI issue](https://app.clickup.com/t/862kfgftm)
- Styles for the hover and regular colors for the number of galleries in the user dropdown have been updated and fixed in light mode.
- The icon size for the hamburger menu button has been updated to `20px x 20px` so it can match the UI.
## Views
- Mobile button size:
- Text colors in user dropdown:
2. In desktop screen view, click on the user dropdown to see the magic ✨ 
3. In mobile view, check the mobile navbar to see the magic ✨ 
-   [ ] I checked my (code) changes for obvious issues, …
=> fix: user dropdown light mode UI issue

resources/js/Pages/Galleries/Components/GalleryGuestBanner/index.tsx
- Class names for `Create gallery` button have been fixed for mobile views, both in light and dark mode.
https://github.com/ArdentHQ/dashbrd/assets/55117912/08622909-e330-43f0-9462-f9dbbdd111fe
=> fix: correct colors for create gallery button

app/Filament/Resources/ArticleResource.php
Rest of rules are already set, metadescription is in another pr, and cover image is not implemented yet so only title length is missing 
https://app.clickup.com/t/8678v0cxa
=> refactor: add title length rule

app/Filament/Resources/ArticleResource.php, app/Filament/Resources/ArticleResource/Pages/CreateArticle.php, app/Filament/Resources/ArticleResource/Pages/EditArticle.php
Adds a multiselect/tag for assigning collections
Closes https://app.clickup.com/t/8678v0cby
=> feat: set article collections

database/seeders/UserSeeder.php
handles the scenario where you have the local user open in a tab while seeding the database
=> fix: handle existing local user when seeding

app/Http/Controllers/CollectionController.php, resources/js/Pages/Collections/Index.tsx
- Collections are now sorted by `Recently Received` by default.
- The filter is also enabled by default in the UI.
1. Run the app in `local` or `testing_e2e` by default.
2. Go to `/collections` page and see the magic ✨ 
https://github.com/ArdentHQ/dashbrd/assets/55117912/c67c0d47-b0ef-45dc-aab4-8e9583e2465c
-   [ ] I added a storybook entry for the component that was added …
=> refactor: sort by recently received by default

app/Console/Commands/FetchCollectionActivity.php, app/Jobs/FetchCollectionActivity.php
It could happen that if activity is "invalid" (spam or something) it will get stuck in this `is_fetching_activity=true` state. Also I increased job duration to accommodate higher number of collections.
=> fix: reset activity state if collection is invalid

app/Support/Web3NftHandler.php
https://app.clickup.com/t/862kg5zc0
Basically added a check to do not run if `activity_updated_at` is not `null`.
=> fix: do not index activity for prior indexed collections when running FetchWalletNfts

app/Models/Collection.php
Closes: https://app.clickup.com/t/862kg3c7e
I used `dashbrd_demo_with_activities.dump` to test the query speed. Here is the result of the query changes:
The collections list query took around ~220ms to finish after the changes it is around ~110ms. Checkout the query and it's analayze result:
**Before:**
```SQL
select
"collections"."id",
"collections"."name",
"collections"."slug",
"collections"."address",
"networks"."chain_id",
"collections"."floor_price",
(fiat_value->'USD')::numeric as floor_price_fiat,
lower(tokens.symbol) as floor_price_currency,
tokens.decimals as floor_price_decimals,
case
when collections.extra_attributes->>'image' = 'null' then null
else collections.extra_attributes->>'image'
end as image,
case
when collections.extra_attributes->>'banner' = 'null' then null
else …
```
=> perf: improve collections sorting query

resources/css/_tables.css, resources/js/Components/Collections/CollectionActions/CollectionActions.tsx, resources/js/Components/Collections/CollectionCard/CollectionCard.tsx, resources/js/Components/Collections/CollectionFloorPrice/CollectionFloorPrice.tsx, resources/js/Components/Collections/CollectionName/CollectionName.tsx, resources/js/Components/Collections/CollectionPortfolioValue/CollectionPortfolioValue.tsx, resources/js/Components/Collections/CollectionsTable/CollectionsTableItem.tsx, resources/js/Components/Table/TableHeader.tsx, resources/js/Components/Tabs.tsx, resources/js/Pages/Collections/Components/CollectionsFilter/CollectionsSorting.tsx
- Dark mode has been enabled for the entire `My collections` page and all its children components.
- Both grid and table collection views now support dark mode.
- `Table` component styles have been updated to support dark mode.
2. Go to `Settings` and turn on the `Dark mode` slider.
3. Go to `/collections` page.
4. Navigate in the page and see the magic ✨ 
https://github.com/ArdentHQ/dashbrd/assets/55117912/27987e6b-db30-45fb-a775-fd17d5cf6d89
-   [ ] I opened a corresponding card on Clickup for any …
=> feat: dark mode for my collections page

resources/js/Components/BalanceHeader/BalanceHeader.skeleton.tsx, resources/js/Components/BalanceHeader/BalanceHeader.tsx, resources/js/Components/BalanceHeader/BalanceHeaderMobile.skeleton.tsx, resources/js/Components/BalanceHeader/BalanceHeaderMobile.tsx, resources/js/Components/Collections/CollectionActivityTable/CollectionActivityTable.blocks.tsx, resources/js/Components/Graphs/DonutGraph/DonutGraph.tsx, resources/js/Components/PortfolioBreakdown/DonutChart.tsx, resources/js/Components/PortfolioBreakdown/PortfolioBreakdownTable.tsx, resources/js/Components/PortfolioBreakdown/PortfolioBreakdownText.tsx, resources/js/Components/PriceChange/PriceChange.tsx, resources/js/Components/Table/Table.tsx, resources/js/Components/Table/TableCell.tsx, resources/js/Components/Table/TableHeader.tsx, resources/js/Components/Table/TableRow.tsx, resources/js/Components/WalletTokens/WalletTokensTable.blocks.tsx, resources/js/Components/WalletTokens/WalletTokensTable.tsx
- Dark mode has been enabled for the entire `My wallet` page and all its children components.
- `Portfolio breakdown` slider now fully supports dark mode.
- `Table` component styles have been updated to support dark mode.
2. Go to `Settings` and turn on the `Dark mode` slider.
3. Click on your user dropdown in the navbar.
4. Then, click on `My wallet` button.
6. Navigate in the page and see the magic ✨ 
https://github.com/ArdentHQ/dashbrd/assets/55117912/1549a19d-ecb9-43a5-99d9-9ba13acbeb28
-   [ ] I …
=> feat: dark mode for my wallet page

app/Models/Article.php, database/migrations/2023_09_20_124432_create_articles_table.php, tests/App/Http/Controllers/ArticleControllerTest.php
https://app.clickup.com/t/86790vqu2
This PR:
- makes `published_at` column `timestamp` instead of `date` because highlighted articles are based on this value, if we publish 2+ articles in a day the order might not be correct because they all will have the same `published_at` value
- makes `sortBy` method consistent with other models
- adds index for the `published_at` as we use this column to sort/filter results
- fixes flaky test
-   [x] I checked my (code) changes for obvious issues, debug statements and commented code
-   [ ] I added a short description on …
=> refactor: articles publish date

app/Filament/Resources/ArticleResource.php
https://app.clickup.com/t/862kh34pk
=> fix: sort articles by published_at by default in admin backend

resources/js/Components/FeaturedCollectionsBanner/FeaturedCollectionsBanner.blocks.tsx
https://app.clickup.com/t/862kh4ex8
=> fix: add carousel key to featured collections to prevent swiper ID collisions

resources/js/Pages/Articles/Components/ArticleMeta.tsx, resources/js/Pages/Articles/Show.tsx
Closes https://app.clickup.com/t/862kh47a3 and fixed this https://app.clickup.com/t/862kh47kw as a side effect
=> fix: article meta & featured collection size as per design

resources/js/Pages/Articles/Components/ArticleMeta.tsx, resources/js/Pages/Articles/Components/ArticleShare.tsx, resources/js/Pages/Articles/Show.tsx
https://app.clickup.com/t/862kh7pw5
=> refactor: move the article copy button to share list

resources/css/_skeletons.css, resources/js/Components/Articles/Article.blocks.tsx, resources/js/Components/Articles/ArticleCard/ArticleCard.tsx, resources/js/Pages/Articles/Index.tsx
- Skeleton loader has been updated for the different variants for article cards, in both light and dark mode.
- As an extra, colors for the dark mode in the count in the header for the articles count has been fixed.
=> refactor: skeleton loader for article cards

resources/js/Pages/Collections/Components/CollectionsHeading/RefreshButton.tsx, resources/js/Pages/Collections/View.tsx, routes/api.php, tests/App/Http/Controllers/RefreshedCollectionControllerTest.php
https://app.clickup.com/t/862khgqbt
=> refactor: disable signature requirement for refresh actions

resources/js/Pages/Collections/Components/CollectionNavigation/CollectionNavigation.tsx, resources/js/Pages/Collections/View.tsx
No task but, see discussion in https://helloardent.slack.com/archives/C04P3DGJJ1W/p1698768310805259
* Preserves the activity table when clicking "refresh" instead of replacing it with "Loading" message block.
* Removes the redundant tooltip on collection activity refresh button (See attached preview)
-   [ ] …
=> fix: remove redundant  tooltip in activity refresh button

resources/js/Pages/Collections/Components/CollectionsHeading/RefreshButton.tsx, resources/js/Pages/Collections/View.tsx
[This pr](https://github.com/ArdentHQ/dashbrd/pull/314/files) added the `authenticatedAction` but in order to work (show the connect modal if session is lost) the axios call need to be async
To test login with your wallet, open the collections page, clear browser data, press refresh, you should see the connect modal.
-   [ ] I added a storybook entry for the component that was added _(if …
=> refactor: use async call in authenticatedAction

resources/js/Components/Report.test.tsx
- `render` method in `Report` test case has been wrapped in `act` util to fix warnings.
- These warnings were related to `headless-ui` implementations in our `Report` component. 
- After trying different ideas from multiple sources, [this one](https://stackoverflow.com/questions/65811507/react-testing-library-an-update-inside-a-test-was-not-wrapped-in-act-can) seemed to be the one that worked perfectly.
- Warnings before this fix:
- Warnings after this fix (none):
1. Run the app tests by using `pnpm test` and see the magic ✨ 
-   [ ] I opened a …
=> fix: test warnings

resources/js/Components/Articles/ArticleCard/ArticleCardSkeleton.tsx
- Dark mode has been added to "More soon" skeleton cards for articles.
2. Remove all the entries in your `articles` table in your local DB.
3. Go to `/articles` page.
4. Turn on dark mode in the navbar and see the magic ✨ 
> Note: Wanted to activate animation for skeleton components, but it seems odd and it was configured to be off, too. Let me know if it is necessary to turn it on.
-   [ ] I added a short description on …
=> refactor: dark mode for more soon article skeleton card

resources/js/Pages/Galleries/MyGalleries/Create.tsx, resources/js/Pages/Galleries/hooks/useGalleryForm.ts
Closes: https://app.clickup.com/t/862kh23eg
Depends on #326  
> “Publish” - publish the current gallery and remove any draft we had for it
It will delete the draft once backend returns success response
> “Cancel” - return to the “My galleries” screen and save the current state as a draft
Left it out as we discussed in Slack: it doesn't seem necessary as we persist stuff once it happens. Only problem could be when user click on `Cancel` button right after inputting the title, but it shouldn't be problem as `onBlur` triggers regardless 
“Delete” - show the [delete modal](https://hackmd.io/7U6LZFILRrOWDkcD-ugauQ#Delete-Modal) if we had saved any data to a draft. If no data was saved yet (e.g. page has no title and no NFTs) then the delete action behaves similar to cancel.
> Left this out too …
=> feat: handle gallery drafts toolbar actions

resources/js/Components/Tooltip/Tooltip.tsx
https://app.clickup.com/t/862kj4y8m
Tooltip changes were introduced by https://github.com/ArdentHQ/dashbrd/pull/301, but I don't see any tasks that indicate tooltip changes.
=> fix: tooltip arrow background color

resources/js/Pages/Galleries/MyGalleries/Index.tsx, resources/js/Pages/Galleries/hooks/useGalleryDrafts.test.ts, resources/js/Pages/Galleries/hooks/useGalleryDrafts.ts, resources/js/databaseConfig.ts
Closes: https://app.clickup.com/t/862kh23f0
> To avoid stale drafts being kept indefinitely, we should store a timestamp of when they were last edited and discard them from localstorage once they are older than 30 days. This will keep drafts up to date with the changes happening to addresses and avoids needless drafts from piling up.
> A way to handle this is to check upon page navigation to the gallery what the age is of the stored drafts and delete any that are expired before showing the list of drafts
-   [x] I checked my (code) changes for obvious issues, debug statements and commented code
-   [ ] I opened a corresponding card on …
=> feat: delete expired drafts

resources/css/_tooltips.css, resources/css/app.css, resources/js/Pages/Articles/Components/ArticleContent.tsx
Closes https://app.clickup.com/t/86dqha718
=> fix: use white tooltip on dark mode on articles

resources/js/Components/Tabs.tsx
- Text color for non-selected tab item in dark mode has been fixed.
1. Run the app in `local` or `testing_e2e`.
2. Make sure your testing wallet has at least 1 token to register.
3. Click on your wallet dropdown from the navbar.
4. Click on `My wallet` button.
5. Once you are on `/wallet` page, click on any token you have registered.
6. Check the slider menu item tabs and see the magic ✨ 
-   [ …
=> fix: text color for non-selected tab item dark mode

resources/js/Components/FeaturedCollectionsBanner/FeaturedCollectionsBanner.blocks.tsx
- Featured collection placeholder now fully supports dark mode.
2. Make sure you have at least 1 NFT in your testing wallet.
3. Click on the `Create gallery` button from the homepage.
4. Scroll down the creation page and see the magic ✨ 
-   [ ] Documentation _(if …
=> fix: featured collection placeholder dark mode

resources/js/Components/Articles/ArticleCard/ArticleCard.tsx
- We now use `break-words` tailwind class to implement `overflow-wrap: break-word` style in our article cards.
- Article titles now fill the 2 lines and also truncate if the title is too long.
1. Run the latest migrations using `composer db:dev`.
2. Go to your database and edit any article you want to test. Remove the spaces, just make it one long word and set more characters if you want.
3. Save the changes in your DB.
4. Run the app in `local` or `testing_e2e` mode.
5. Go to `/articles` page.
6. Look for the article you edited and see the magic ✨ 
- Main card:
- Regular card:
-   [ ] I checked my (code) changes for obvious issues, debug …
=> fix: break words in article card

resources/js/Pages/Galleries/MyGalleries/Index.tsx
- "No galleries" placeholder will not be shown anymore if we have no galleries but drafts.
2. Make sure you have at least 1 NFT in your testing wallet.
4. Make sure you have not created any gallery. If so, remove them.
3. Click on `Create a gallery` from the homepage.
5. Click on another page and go to `/my-galleries` page.
6. Select `Drafts` item in the side menu and see the magic ✨ 
## Screenshot
-   [ ] I added a …
=> fix: remove placeholder when gallery drafts exist

app/Http/Controllers/RefreshedNftController.php, tests/App/Http/Controllers/RefreshedNftControllerTest.php
https://app.clickup.com/t/86dqhafcg
Even though the `FetchCollectionActivity` job will in fact [check for supply](https://github.com/ArdentHQ/dashbrd/blob/develop/app/Jobs/FetchCollectionActivity.php#L58), there's no need even to dispatch the job if we don't support activity for the collection (no supply, hard cap or blacklisted).
-   [ ] I added a storybook entry for the component that was …
=> refactor: ignore activity for invalid collections when refreshing NFT metadata

resources/js/Components/Clipboard/Clipboard.tsx, resources/js/Pages/Articles/Components/ArticleCopy.tsx
https://app.clickup.com/t/86dqhagtm
It still defaults to "default" behavior (top) in other places:
=> refactor: place tooltip of article's "copy" button on the left

resources/js/Pages/Galleries/MyGalleries/Components/MyGalleryListboxMenu.tsx, resources/js/Pages/Galleries/MyGalleries/Components/MyGallerySidebar.tsx
https://app.clickup.com/t/86dqhagx1
Since we load drafts async and it might take a bit, this PR keeps it disabled during this "loading" phase.
=> refactor: disable sidebar item if there are no drafts

resources/js/Components/Collections/CollectionActions/CollectionActions.test.tsx
Closes https://app.clickup.com/t/86dqhbga7 
=> test: fix flaky in `CollectionActions`

resources/js/Components/Galleries/NftGalleryCard.blocks.tsx
Closes: https://app.clickup.com/t/86dqhg50t
=> fix: create gallery NFT image border color in dark mode

resources/js/Pages/Galleries/MyGalleries/Create.tsx, resources/js/Pages/Galleries/hooks/useWalletDraftGalleries.ts, resources/js/Pages/Galleries/hooks/useWalletDraftGallery.ts
Closes https://app.clickup.com/t/86dqk1uey 
=> fix: delete draft if empty when navigating away

app/Http/Controllers/CollectionController.php
- Login requirement has been removed from collections overview page.
1. Run the app in `local` mode.
2. Make sure you have your wallet disconnected.
3. Go to `/collections` page and see the magic ✨ 
=> fix: remove login requirement for collections overview page

app/Filament/Resources/CollectionResource.php
- Admin cannot mark more than 4 collections as `featured` on the admin panel.
- We will display a warning alert instead.
1. Run the app in `local` mode.
2. Go to `/admin` panel.
3. Log in as an admin or super-admin.
4. Click on collections item.
5. Mark 4 collections as featured.
6. Try to mark a 5th one and see the magic ✨ 
https://github.com/ArdentHQ/dashbrd/assets/55117912/a06eee7c-74da-48da-8f7f-9ec38a520166
-   [ ] I added a short description on how to test this …
=> refactor: limit featured collections to 4 on admin panel

resources/js/Pages/Galleries/MyGalleries/Index.tsx
- Paddings have been fixed for galleries and draft cards in mobile view. It now matches the design.
2. Make sure your wallet is connected.
3. Create at least 1 gallery and 1 draft.
4. Go to `/my-galleries` page and see the magic ✨ 
-   [ ] Documentation _(if …
=> fix: add padding for galleries and draft cards in my galleries page

resources/js/Components/Carousel/Carousel.test.tsx, resources/js/Components/Carousel/Carousel.tsx, resources/js/Components/Carousel/Hooks/useCarouselAutoplay.test.ts, resources/js/Components/Carousel/Hooks/useCarouselAutoplay.ts, resources/js/Components/Collections/CollectionActions/CollectionActions.test.tsx, resources/js/Pages/Collections/Components/CollectionNft/CollectionNft.tsx, resources/js/Pages/Collections/Components/FeaturedCollections/FeaturedCollectionNfts.tsx, resources/js/Pages/Collections/Components/FeaturedCollections/FeaturedCollectionsCarousel.tsx, resources/js/Pages/Collections/Components/FeaturedCollections/FeaturedCollectionsItem.tsx, tailwind.config.js
Depends on https://github.com/ArdentHQ/dashbrd/pull/494
Closes https://app.clickup.com/t/86dqk29xp
* Adds carousel pagination (bars)
* Autoplay is on by default
* The active pagination bar shows the remaining time until next slide.
-   [x] …
=> refactor: adjust collection carousel ui

resources/js/Pages/Collections/Components/FeaturedCollections/FeaturedCollectionsCarousel.tsx
Follow-up fix for https://github.com/ArdentHQ/dashbrd/pull/505#pullrequestreview-1750962041
Sets the `rewind` prop by default in featured collections carousel, to always display the arrows.
=> fix: rewind featured collections carousel

resources/js/Pages/Articles/Components/ArticlesView.tsx
- The correct placeholder is now displayed when we have 0 articles to display for a collection with the following message: `No articles have been linked to this collection as of now`.
2. Make sure your testing wallet has a collection with no articles attached.
3. This can simply be done by running `php artisan horizon` and loading new collections.
4. Go to `/collections` page.
5. Select any new collection with no articles.
6. Click on `Articles` tab and see the magic ✨ 
-   [ ] I …
=> fix: display placeholder for articles tab

resources/js/Pages/Articles/Components/ArticlesView.tsx
- Spacing for empty blocks in the articles tab from collections page has been fixed.
- Collection with articles:
- Collection with no articles:
=> fix: adjust spacing for empty blocks in articles tab

app/Console/Commands/FetchCollectionFloorPrice.php
Closes: https://app.clickup.com/t/86dqj94tz
The `FetchCollectionFloorPrice` job is being delayed with an async closure;  this closure is adding the original job to the queue again, but it's not necessarily dispatched immediately, to resolve that changed  `dispatch` to `dispatchSync`
-   [ ] Documentation _(if …
=> refactor: make FetchCollectionFloorPrice dispatch in sync

resources/js/Pages/Collections/Index.tsx
https://app.clickup.com/t/86dqp1rwk
1024px:
768px:
=> fix: whitespace above featured collections

app/Http/Client/Alchemy/AlchemyPendingRequest.php, tests/App/Jobs/FetchWalletNftsTest.php
Closes: https://app.clickup.com/t/86dqpedrv
This PR removes `tokenId` decoding functionality, it is no longer needed as Alchemy V3 API handles it automatically.
https://docs.alchemy.com/reference/nft-api-v2-to-v3-migration-guide#overview-of-changes-in-nft-api-v3
> Decimal String token IDs: All token IDs are now served as decimal strings. In V2, token IDs were sometimes served as hexadecimal or decimal strings, which could lead to confusion and potential errors.
-   [x] I checked my (code) changes for obvious issues, debug statements and commented code
-   [ ] …
=> fix: disable `tokenId` decoding for Alchemy endpoints

database/migrations/2023_12_11_202944_create_floor_price_history_table.php
Fixes the error when running `php artisan migrate`
```
INFO  Running migrations.  
2023_12_11_202944_create_floor_price_history_table ................ 3ms FAIL
BadMethodCallException 
Method Tpetry\PostgresqlEnhanced\Schema\Grammars\Grammar::typeNumeric does not exist.
``` …
=> fix: add `typeNumeric` macro to migration

resources/js/Pages/Collections/MyCollections/Index.tsx
Fixes sorting URL for my collections page.
=> fix: use my collections URL for sorting

app/Console/Kernel.php, app/Data/Collections/VotableCollectionData.php, app/Http/Controllers/CollectionController.php, app/Http/Controllers/CollectionVoteController.php, app/Jobs/FetchCollectionVolume.php, app/Jobs/ResetCollectionMonthlyVotesAndRank.php, app/Models/Collection.php, database/migrations/2023_12_21_152434_add_monthly_rank_to_collections_table.php, queries/collections.calculate_monthly_rank_and_votes_value.sql, queries/collections.calculate_monthly_rank_value.sql, tests/App/Jobs/ResetCollectionMonthlyVotesAndRankTest.php, tests/App/Models/CollectionTest.php
Stores the monthly_votes and monthly_rank on the collections table as some kind of cache and update the value every time a new vote is added or volume changes
with those values we can dramatically improve the queries https://app.clickup.com/t/86dqwza8z
-   [ ] Tests _(if …
=> refactor: optimize collections page

app/helpers.php
https://app.clickup.com/t/86dqp2uyk
On the ClickUp card, I have concluded that those queries are always properly read from the filesystem, but the problem is when it comes to processing them with Blade. Blade does in fact compile them and writes the compiled version to a file in a temporary directory, but when it reads the compiled view back, it's empty.
The problem of Blade not reading the file is still a bit of a mystery. I still suspect it's something to do with CI setup with race condition between CI filesystem and booting the framework, as this never happens once the framework is fully loaded.
However, all migration files use a simple string without any custom parameters (variables) that might benefit from compiling with Blade. If there are no parameters, we can just avoid rendering …
=> fix: do not use Blade to render custom query if there are no parameters

resources/js/Components/Collections/CollectionsFullTable/CollectionsFullTable.test.tsx
https://app.clickup.com/t/86dr4qwr4
We test that N/A is shown when supply is `null`, but we don't explicitly check that N/A is not shown if supply is not `null`. This edge case is sometimes triggered by model factory which sets `supply` as random value, including `null`.
- …
=> fix: flaky test in UI components

resources/js/Components/Tabs.test.tsx, resources/js/Components/Tabs.tsx
https://app.clickup.com/t/86dr5a3fu
=> fix: text color on the tab button should be `primary-900`

resources/js/Components/Articles/Article.blocks.test.tsx, resources/js/Components/Articles/Article.blocks.tsx
https://app.clickup.com/t/86dr5vnfu
=> fix: "featured collections" overflows onto the next line on 768px

app/Console/Commands/LiveDumpNfts.php, app/Console/Commands/LiveDumpWallets.php, app/Contracts/Web3DataProvider.php, app/Http/Client/Alchemy/AlchemyPendingRequest.php, app/Http/Client/Mnemonic/MnemonicPendingRequest.php, app/Http/Client/Moralis/MoralisPendingRequest.php, app/Http/Client/Opensea/OpenseaPendingRequest.php, app/Jobs/FetchCollectionBanner.php, app/Jobs/FetchCollectionFloorPrice.php, app/Jobs/FetchCollectionOwners.php, app/Jobs/FetchCollectionTraits.php, app/Jobs/FetchCollectionVolume.php, app/Services/Web3/Alchemy/AlchemyWeb3DataProvider.php, app/Services/Web3/Fake/FakeWeb3DataProvider.php, app/Services/Web3/Mnemonic/MnemonicWeb3DataProvider.php, app/Services/Web3/Moralis/MoralisWeb3DataProvider.php, app/Services/Web3/Opensea/OpenseaWeb3DataProvider.php, app/Support/Facades/Alchemy.php, app/Support/Facades/Mnemonic.php, app/Support/Facades/Moralis.php, app/Support/Facades/Opensea.php, config/dashbrd.php, tests/App/Http/Client/Mnemonic/MnemonicPendingRequestTest.php, tests/App/Http/Client/Moralis/MoralisPendingRequestTest.php, tests/App/Http/Client/Opensea/OpenseaPendingRequestTest.php, tests/App/Services/Web3/Alchemy/AlchemyWeb3DataProviderTest.php, tests/App/Services/Web3/Mnemonic/MnemonicWeb3DataProviderTest.php, tests/App/Services/Web3/Moralis/MoralisWeb3DataProviderTest.php, tests/App/Services/Web3/Opensea/OpenseaWeb3DataProviderTest.php, tests/App/Support/Facades/MnemonicTest.php
https://app.clickup.com/t/86dr79awa
=> refactor: rename `getNftCollection*` methods to `getCollection*`

app/Models/Token.php, app/Models/Traits/BelongsToNetwork.php, tests/App/Models/CollectionTest.php, tests/App/Models/TokenTest.php
Will be needed for #611, but decided to do this in another PR to keep things light. This adds 2 methods to the Token model.
1. `currentPrice($currency)` -> gets the current fiat price for a token from its meta attributes
2. `toCurrentFiat($value, $currency)` -> gets the current fiat value from some crypto value. It uses BigNumber library as these values can be very large numbers.
-   [ ] I …
=> refactor: add methods to convert crypto to current fiat price of a token

tests/App/Models/CollectionVoteTest.php
https://app.clickup.com/t/86dr9z7ef
The problem was that `addVote` runs `updateOrCreate()`, but on top of the wallet ID it also checks uniqueness of `voted_at`. If `voted_at` is even one second after the previous one, it would create a new vote instead of update existing one. So this occasionally happened.
-   [ …
=> fix: flaky collection vote test

app/Data/Collections/CollectionOfTheMonthData.php, app/Models/CollectionWinner.php, app/Models/Traits/HasVolume.php, resources/js/Pages/Collections/Components/WinnerCollections/WinnerCollections.blocks.tsx, resources/js/Tests/Factories/Collections/CollectionOfTheMonthFactory.ts, resources/types/generated.d.ts, tests/App/Http/Controllers/CollectionOfTheMonthControllerTest.php
https://app.clickup.com/t/86draum2a
=> refactor: use 30-day volume for previous "cotm" winners

app/Data/Collections/CollectionFeaturedData.php
https://app.clickup.com/t/86drd4kbd
=> fix: strip markdown from a featured collection's description

app/Http/Client/Opensea/OpenseaPendingRequest.php, config/services.php
https://app.clickup.com/t/86drgahvk
The problem is that we used to cache the entire OpenSea response, which is serialized and put into Redis, then deserialized. It can't properly be deserialized, and thus failed. We can cache the JSON response, though. That can be serialized with no issues.
As a bonus, I inlined the OpenSea API URL and the version as there is no more v1.
What we did:
```php
Cache::remember('key', $ttl, fn () => Http::get('/some-endpoint'));
```
What we need to do:
```php
Cache::remember('key', $ttl, fn () => Http::get('/some-endpoint')->json());
```
When testing **and after deployment,** please clear cache: `php artisan cache:clear`
To test, set cache driver to redis, open tinker, and run the following code twice `Opensea::getCollectionFloorPrice('proof-moonbirds')`.
``` …
```
=> fix: caching the opensea response causing the `TypeError` when deserializing

database/seeders/CollectionFloorPriceHistorySeeder.php
https://app.clickup.com/t/86drtcq5v
If you run `composer db:live` and open the "filter" button on the My Collections page, you'll see a bunch of networks generated. The problem was that when we use `FloorPriceHistory` factory, we'll automatically create a new token for each floor price entry, which will create a new network. We can reuse that token from the collection.
-   [ ] I added a …
=> fix: prevent extra networks from being created while seeding

resources/js/Components/Collections/CollectionName/NominateCollectionName.tsx, resources/js/Components/Collections/PopularCollectionsTable/PopularCollectionsTable.blocks.tsx, resources/js/Pages/Collections/Components/CollectionVoting/VoteCollections.tsx, resources/js/Pages/Collections/Components/WinnerCollections/WinnerCollections.blocks.tsx, resources/js/Utils/Currency.test.tsx, resources/js/Utils/Currency.tsx
https://app.clickup.com/t/86drpncbr
=> refactor: add utility to format the volume data

app/Data/Web3/Web3NftData.php, app/Support/Web3NftHandler.php
https://app.clickup.com/t/86drjzff1
=> refactor: hydrate the Collection model when persisting to database

resources/js/Components/Articles/ArticleCard/ArticleErrorImage.tsx, resources/js/Components/Collections/CollectionDescription/CollectionDescription.tsx, resources/js/Components/ErrorBlock/ErrorBlock.blocks.tsx, resources/js/Components/Form/TextInput/TextInput.tsx, resources/js/Components/Navbar/MobileMenu.tsx, resources/js/Components/PortfolioBreakdown/Hooks/usePriceChart.ts, resources/js/Components/Skeleton/Skeleton.tsx, resources/js/Pages/Articles/Show.tsx, resources/js/Utils/assertions.ts
https://app.clickup.com/t/86drj8rbd
There are some places in React where we have some value be either some object or `null`. We can avoid calls to `isTruthy` in these situations as it's simple enough to check whether some value is `null` or `undefined`.
Also, if some component prop is an optional boolean, we can default to `false`, such as in the `TextInput` component, to avoid this prop being possibly `undefined`.
For example:
```tsx
interface Props {
isDisabled?: boolean;
}
function SomeComponent({ isDisabled = false }: Props) {
// isDisabled is now always boolean and doesn't need `isTruthy` call
}
```
Just uses more TypeScript to make a nicer developer experience.
-   [ ] I checked my UI changes for …
=> refactor: avoid `isTruthy` call in places where it's not needed

app/Models/Traits/HasFloorPriceHistory.php, tests/App/Models/CollectionTest.php
https://app.clickup.com/t/86drvxaue
=> fix: divison by zero when there is no yesterday's floor price

.gitignore
I noticed when I run tests that `.phpunit.cache` file is there to be committed. Maybe they changed something as it was previously called `.phpunit.result.cache`
=> chore: add phpunit cache to gitignore
